# Generated by Django 2.2.7 on 2019-11-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mody',
            new_name='body',
        ),
    ]
